create table "public"."Survey_Responses" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "data_entry" jsonb,
    "survey_id" uuid
);


alter table "public"."Survey_Responses" enable row level security;

create table "public"."Survey_Summaries" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "survey_id" uuid,
    "summary_data" jsonb,
    "updated_at" timestamp with time zone default now()
);


alter table "public"."Survey_Summaries" enable row level security;

CREATE UNIQUE INDEX "Survey_Response_pkey" ON public."Survey_Responses" USING btree (id);

CREATE UNIQUE INDEX "Survey_Summaries_pkey" ON public."Survey_Summaries" USING btree (id);

alter table "public"."Survey_Responses" add constraint "Survey_Response_pkey" PRIMARY KEY using index "Survey_Response_pkey";

alter table "public"."Survey_Summaries" add constraint "Survey_Summaries_pkey" PRIMARY KEY using index "Survey_Summaries_pkey";

alter table "public"."Survey_Responses" add constraint "Survey_Response_survey_id_fkey" FOREIGN KEY (survey_id) REFERENCES "Surveys"(id) not valid;

alter table "public"."Survey_Responses" validate constraint "Survey_Response_survey_id_fkey";

alter table "public"."Survey_Summaries" add constraint "Survey_Summaries_survey_id_fkey" FOREIGN KEY (survey_id) REFERENCES "Surveys"(id) not valid;

alter table "public"."Survey_Summaries" validate constraint "Survey_Summaries_survey_id_fkey";

grant delete on table "public"."Survey_Responses" to "anon";

grant insert on table "public"."Survey_Responses" to "anon";

grant references on table "public"."Survey_Responses" to "anon";

grant select on table "public"."Survey_Responses" to "anon";

grant trigger on table "public"."Survey_Responses" to "anon";

grant truncate on table "public"."Survey_Responses" to "anon";

grant update on table "public"."Survey_Responses" to "anon";

grant delete on table "public"."Survey_Responses" to "authenticated";

grant insert on table "public"."Survey_Responses" to "authenticated";

grant references on table "public"."Survey_Responses" to "authenticated";

grant select on table "public"."Survey_Responses" to "authenticated";

grant trigger on table "public"."Survey_Responses" to "authenticated";

grant truncate on table "public"."Survey_Responses" to "authenticated";

grant update on table "public"."Survey_Responses" to "authenticated";

grant delete on table "public"."Survey_Responses" to "service_role";

grant insert on table "public"."Survey_Responses" to "service_role";

grant references on table "public"."Survey_Responses" to "service_role";

grant select on table "public"."Survey_Responses" to "service_role";

grant trigger on table "public"."Survey_Responses" to "service_role";

grant truncate on table "public"."Survey_Responses" to "service_role";

grant update on table "public"."Survey_Responses" to "service_role";

grant delete on table "public"."Survey_Summaries" to "anon";

grant insert on table "public"."Survey_Summaries" to "anon";

grant references on table "public"."Survey_Summaries" to "anon";

grant select on table "public"."Survey_Summaries" to "anon";

grant trigger on table "public"."Survey_Summaries" to "anon";

grant truncate on table "public"."Survey_Summaries" to "anon";

grant update on table "public"."Survey_Summaries" to "anon";

grant delete on table "public"."Survey_Summaries" to "authenticated";

grant insert on table "public"."Survey_Summaries" to "authenticated";

grant references on table "public"."Survey_Summaries" to "authenticated";

grant select on table "public"."Survey_Summaries" to "authenticated";

grant trigger on table "public"."Survey_Summaries" to "authenticated";

grant truncate on table "public"."Survey_Summaries" to "authenticated";

grant update on table "public"."Survey_Summaries" to "authenticated";

grant delete on table "public"."Survey_Summaries" to "service_role";

grant insert on table "public"."Survey_Summaries" to "service_role";

grant references on table "public"."Survey_Summaries" to "service_role";

grant select on table "public"."Survey_Summaries" to "service_role";

grant trigger on table "public"."Survey_Summaries" to "service_role";

grant truncate on table "public"."Survey_Summaries" to "service_role";

grant update on table "public"."Survey_Summaries" to "service_role";

create policy "Enable all for owner users of the responded survey"
on "public"."Survey_Responses"
as permissive
for all
to public
using ((( SELECT auth.uid() AS uid) = ( SELECT "Surveys".owner
   FROM "Survey_Responses" "Survey_Responses_1",
    "Surveys"
  WHERE ("Surveys".id = "Survey_Responses_1".survey_id))));


create policy "Enable all for owner users of the summarized survey"
on "public"."Survey_Summaries"
as permissive
for select
to public
using ((( SELECT auth.uid() AS uid) = ( SELECT "Surveys".owner
   FROM "Survey_Summaries" "Survey_Summaries_1",
    "Surveys"
  WHERE ("Surveys".id = "Survey_Summaries_1".survey_id))));



